import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={``}>
        {children}
      </body>
    </html>
  );
}
